Repository netlify/netlify-credential-helper, pull requests merged in 2021-02, with the labels that each got.

#50 ci: switch to github actions
  .github/workflows/main.yml
  azure-pipelines-template.yml
  azure-pipelines.yml
Labels: type: chore

#51 fix: load token from shared config dir
  credentials/auth.go
  credentials/auth_test.go
  go.mod
  go.sum
Labels: type: bug

#53 fix(docs): update release process
  README.md
Labels: type: bug

#48 github tools: fix fossa workflow file
  .github/workflows/fossa.yml
Labels: type: chore

#55 fix(docs): remove plugin installation part from readme
  README.md
Labels: type: feature
